import { LEDProfile, BlogArticle, ProjectPortfolioItem } from './types';

export const PROFILES: LEDProfile[] = [
  // --- MOVELARIA ---
  {
    id: 'psl0018',
    name: 'Perfil LED Embutir Movelaria 9x13mm',
    code: 'PSL0018',
    type: 'movelaria',
    category: 'Movelaria',
    width: 9,
    height: 13,
    description: 'Perfil de iluminação compacto para móveis, forros, painéis de MDF e corian. Encaixe preciso nivelado à superfície com luz contínua de alta qualidade.',
    applications: ['Marcenaria fina e armários', 'Nichos e prateleiras de MDF', 'Closets e guarda-roupas', 'Espelhos e frentes de gaveta'],
    features: ['Travas de fixação ocultas', 'Excelente dissipação com fita LED COB', 'Difusor branco translúcido em acrílico PMMA'],
    maxStripWidth: '8mm',
    diffuser: 'Acrílico Translúcido Leitoso PMMA',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: true,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0020',
    name: 'Perfil LED Embutir Movelaria 24x7mm',
    code: 'PSL0020',
    type: 'movelaria',
    category: 'Movelaria',
    width: 24,
    height: 7,
    description: 'Perfil de embutir ultra-slim para móveis e divisórias. Altura reduzida de apenas 7mm, permitindo instalação em chapas finas de marcenaria sem comprometer a estrutura.',
    applications: ['Prateleiras de madeira sob medida', 'Painéis ripados de baixa espessura', 'Móveis de cozinha aéreos', 'Cabeceiras estofadas e MDF'],
    features: ['Design extra plano de 7mm', 'Instalação simples por presilhas de pressão', 'Compatível com fitas COB de alta potência'],
    maxStripWidth: '10mm',
    diffuser: 'Policarbonato Difusor Opalino Anti-UV',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: true,
    image: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0021',
    name: 'Perfil LED Embutir Movelaria 24x14mm',
    code: 'PSL0021',
    type: 'movelaria',
    category: 'Movelaria',
    width: 24,
    height: 14,
    description: 'Perfil para iluminação interna de móveis de alto padrão. Oferece câmara ótica de 14mm para eliminar completamente os pontos visíveis de LED.',
    applications: ['Closets e vitrines comerciais', 'Prateleiras de cozinhas e cristaleiras', 'Painéis decorativos de madeira', 'Estantes e bibliotecas'],
    features: ['Elimina o efeito pontilhado (No-dot)', 'Abas laterais elegantes para cobertura perfeita', 'Alta taxa de transmitância luminosa'],
    maxStripWidth: '12mm',
    diffuser: 'Acrílico Leitoso com Difusão Homogênea',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: true,
    image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0001',
    name: 'Perfil LED Sobrepor Movelaria 8x9mm',
    code: 'PSL0001',
    type: 'movelaria',
    category: 'Movelaria',
    width: 8,
    height: 9,
    description: 'Perfil plano ultra-discreto para sobrepor em superfícies com restrição de altura. Perfeito para aplicação sob armários e gavetas.',
    applications: ['Sob armários aéreos de cozinha', 'Iluminação interna de gavetas', 'Prateleiras expostas de vidro', 'Espelhos de banheiros'],
    features: ['Dimensão reduzida 8x9mm', 'Fixação direta limpa', 'Acompanha ponteiras e travas de fixação'],
    maxStripWidth: '8mm',
    diffuser: 'Policarbonato Fosco Acetinado',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: true,
    image: 'https://images.unsplash.com/photo-1541123437800-1bb1317badc2?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0003',
    name: 'Perfil LED Sobrepor Movelaria 17x14mm',
    code: 'PSL0003',
    type: 'movelaria',
    category: 'Movelaria',
    width: 17,
    height: 14,
    description: 'Perfil robusto de sobrepor para marcenaria e iluminação funcional. Ótima dissipação térmica para fitas LED de maior wattage.',
    applications: ['Bancadas de trabalho e home office', 'Balcões de atendimento e recepção', 'Prateleiras pesadas', 'Iluminação sob nichos'],
    features: ['Perfil estruturado resistente', 'Montagem rápida sobre MDF ou alvenaria', 'Compatível com múltiplos acessórios'],
    maxStripWidth: '10mm',
    diffuser: 'Acrílico Difusor PMMA',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: true,
    image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=800&auto=format&fit=crop',
  },

  // --- EMBUTIR ---
  {
    id: 'psl0019',
    name: 'Perfil LED Embutir Assimétrico 10x30mm',
    code: 'PSL0019',
    type: 'embutir',
    category: 'Embutir',
    width: 30,
    height: 10,
    description: 'Perfil de iluminação com facho de luz assimétrico direcionado, ideal para lavagem de paredes (wall washing) e contornos decorativos.',
    applications: ['Iluminação de destaque em paredes e quadros', 'Corredores e halls residenciais', 'Sinalização teto-parede', 'Recepções corporativas'],
    features: ['Facho de luz inclinado e direcionado', 'Proporciona iluminação indireta sem ofuscamento', 'Alumínio de alta pureza anodizado'],
    maxStripWidth: '10mm',
    diffuser: 'Policarbonato Asimétrico Difusor',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0022',
    name: 'Perfil LED Embutir com Aba 24x14mm',
    code: 'PSL0022',
    type: 'embutir',
    category: 'Embutir',
    width: 24,
    height: 14,
    description: 'Perfil clássico de embutir com abas laterais. Modelo mais vendido para rasgos de luz em forros de gesso e sancas residenciais.',
    applications: ['Rasgos de luz em teto de gesso e drywall', 'Iluminação geral em salas e quartos', 'Escritórios e salas de reunião', 'Corredores e passagens'],
    features: ['Abas laterais de acabamento perfeito', 'Suporta fitas de LED até 240 LEDs/m', 'Fixação firme por presilhas metálicas inclusas'],
    maxStripWidth: '12mm',
    diffuser: 'Policarbonato Translúcido Leitoso PMMA',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0023',
    name: 'Perfil LED Embutir 31x9mm',
    code: 'PSL0023',
    type: 'embutir',
    category: 'Embutir',
    width: 31,
    height: 9,
    description: 'Perfil slim largo de embutir. Oferece abas laterais estendidas para acabamento impecável em juntas de gesso ou painéis de parede.',
    applications: ['Teto de drywall e marcenaria de grande largura', 'Painéis de TV e cabeceiras', 'Salas de estar e salas de jantar', 'Lojas e showrooms'],
    features: ['Formato plano e discreto', 'Área de difusão mais larga', 'Acompanha travas e tampas de acabamento'],
    maxStripWidth: '12mm',
    diffuser: 'Acrílico Leitoso Anti-UV',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0024',
    name: 'Perfil LED Embutir 35x20mm',
    code: 'PSL0024',
    type: 'embutir',
    category: 'Embutir',
    width: 35,
    height: 20,
    description: 'Perfil médio/largo com 20mm de profundidade. Ideal para projetos luminotécnicos que exigem alto fluxo luminoso sem marcação de pontos.',
    applications: ['Iluminação principal em ambientes residenciais', 'Projetos arquitetônicos corporativos', 'Restaurantes e recepções de hotéis', 'Salas de reunião'],
    features: ['Câmara profunda para difusão contínua 100%', 'Estrutura reforçada de dissipação', 'Compatível com fitas de até 120 LEDs/m'],
    maxStripWidth: '15mm',
    diffuser: 'Acrílico Opalino de Alta Transmitância',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0025',
    name: 'Perfil LED Embutir 35x22mm',
    code: 'PSL0025',
    type: 'embutir',
    category: 'Embutir',
    width: 35,
    height: 22,
    description: 'Perfil de embutir profundo para projetos imponentes. Permite a instalação de fitas duplas ou fitas de altíssima densidade.',
    applications: ['Áreas sociais e salas integradas', 'Consultórios e clínicas', 'Lojas e galerias de arte', 'Salas de conferência'],
    features: ['Suporta fitas duplas em paralelo', 'Máxima homogeneidade luminosa', 'Excelente durabilidade do alumínio anodizado'],
    maxStripWidth: '18mm',
    diffuser: 'Policarbonato Difusor PMMA Leitoso',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0026',
    name: 'Perfil LED Embutir 46x12mm',
    code: 'PSL0026',
    type: 'embutir',
    category: 'Embutir',
    width: 46,
    height: 12,
    description: 'Perfil extra largo de embutir com abas estendidas. Cria linhas de luz largas marcantes em gesso e madeira.',
    applications: ['Rasgos de luz largos em halls e recepções', 'Corredores de hotéis e escritórios', 'Lojas de moda e vitrines', 'Projetos residenciais modernos'],
    features: ['Linha de luz imponente de 46mm de largura', 'Superfície difusora acetinada', 'Travas de fixação de ação rápida'],
    maxStripWidth: '20mm',
    diffuser: 'Acrílico Opalino Fosco',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0027',
    name: 'Perfil LED Embutir Tabica 47x40mm',
    code: 'PSL0027',
    type: 'embutir',
    category: 'Embutir',
    width: 47,
    height: 40,
    description: 'Perfil especial para aplicação em tabica metálica de forro de gesso. Cria o efeito visual de teto flutuante com luz indireta perfeita.',
    applications: ['Perímetro de tetos em gesso e drywall', 'Efeito de teto flutuante em salas e quartos', 'Sancas perimetrais integradas', 'Áreas corporativas'],
    features: ['Estrutura técnica para substituição de tabica tradicional', 'Iluminação indireta suave voltada para a parede', 'Acabamento limpo em alumínio'],
    maxStripWidth: '12mm',
    diffuser: 'Difusor de Policarbonato Anti-Ofuscamento',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0028',
    name: 'Perfil LED Embutir 50x35mm',
    code: 'PSL0028',
    type: 'embutir',
    category: 'Embutir',
    width: 50,
    height: 35,
    description: 'Perfil arquitetônico largo de alta potência. Projetado para funcionar como fonte de iluminação principal em grandes ambientes.',
    applications: ['Iluminação principal em escritórios e salas', 'Halls de entrada de edifícios e hotéis', 'Auditórios e salas de aula', 'Espaços comerciais'],
    features: ['Suporta fitas duplas paralelas de alta potência', 'Excelente gerenciamento térmico', 'Difusão total sem sombras'],
    maxStripWidth: '24mm',
    diffuser: 'Acrílico Leitoso Especial PMMA',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0029',
    name: 'Perfil LED Embutir Recuado 50x35mm',
    code: 'PSL0029',
    type: 'embutir',
    category: 'Embutir',
    width: 50,
    height: 35,
    description: 'Perfil recuado de alto conforto visual. O difusor fica posicionado no fundo do perfil, reduzindo o ofuscamento direto.',
    applications: ['Salas de TV e home theater', 'Dormitórios e áreas de descanso', 'Escritórios com estações de computador', 'Salas de reuniões'],
    features: ['Foco antiofuscante com difusor recuado', 'Conforto visual certificado', 'Visual arquitetônico sofisticado'],
    maxStripWidth: '20mm',
    diffuser: 'Acrílico Difusor Antireflexo',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0030',
    name: 'Perfil LED Embutir Wall Washer 66x38mm',
    code: 'PSL0030',
    type: 'embutir',
    category: 'Embutir',
    width: 66,
    height: 38,
    description: 'Perfil banhador de parede (Wall Washer) de embutir. Projetado com calha refletora parabólica para banhar paredes uniformemente.',
    applications: ['Banho de luz em paredes de pedra, tijolo ou texturizadas', 'Galerias de arte e exposições', 'Recepções e fachadas internas', 'Salas de estar em destaque'],
    features: ['Lente óptica reflexiva de alta precisão', 'Banhamento uniforme do topo ao piso', 'Construção reforçada'],
    maxStripWidth: '15mm',
    diffuser: 'Lente Parabólica com Difusor Direcionador',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0031',
    name: 'Perfil LED Embutir 71x18mm',
    code: 'PSL0031',
    type: 'embutir',
    category: 'Embutir',
    width: 71,
    height: 18,
    description: 'Perfil plano extra largo para teto e parede. Cria faixas luminosas marcantes em projetos minimalistas contemporâneos.',
    applications: ['Iluminação decorativa de impacto em grandes salas', 'Corredores corporativos e shopping centers', 'Salas de conferência', 'Vitrines'],
    features: ['Extrema largura de 71mm', 'Estrutura plana de embutir', 'Instalação rápida com presilhas estendidas'],
    maxStripWidth: '30mm',
    diffuser: 'Policarbonato Translúcido PMMA',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0034',
    name: 'Perfil LED Embutir Rodapé 100x18mm',
    code: 'PSL0034',
    type: 'embutir',
    category: 'Embutir',
    width: 100,
    height: 18,
    description: 'Perfil metálico estrutural para rodapé iluminado. Integra o rodapé ao piso com luz de balizamento voltada para baixo.',
    applications: ['Rodapé iluminado em corredores e salas', 'Balizamento noturno em suítes e banheiros', 'Hotéis e clínicas de saúde', 'Restaurantes'],
    features: ['Substitui o rodapé convencional', 'Resistente a impactos e limpeza de piso', 'Luz indireta orientada para o chão'],
    maxStripWidth: '12mm',
    diffuser: 'Acrílico Reforçado Anti-Impacto',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800&auto=format&fit=crop',
  },

  // --- SOBREPOR ---
  {
    id: 'psl0002',
    name: 'Perfil LED Sobrepor 17x7mm',
    code: 'PSL0002',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 17,
    height: 7,
    description: 'Perfil plano de sobrepor ultra-discreto. Aplicação direta em superfícies rígidas como lajes, marcenaria e alvenaria sem necessidade de corte.',
    applications: ['Iluminação sob armários de cozinha', 'Prateleiras e nichos decorativos', 'Cabeceiras de cama', 'Espelhos'],
    features: ['Apenas 7mm de espessura externa', 'Instalação rápida por presilhas metálicas', 'Acabamento limpo e durável'],
    maxStripWidth: '10mm',
    diffuser: 'Policarbonato Opalino PMMA',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: true,
    image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0004',
    name: 'Perfil LED Sobrepor Com Recuado 17x14mm',
    code: 'PSL0004',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 17,
    height: 14,
    description: 'Perfil de sobrepor com recuo do difusor. Combina a facilidade de instalação de sobrepor com o conforto visual do facho recuado.',
    applications: ['Home-office e bancadas de estudo', 'Corredores e passagens', 'Lojas e expositores de produtos', 'Salas de estar'],
    features: ['Efeito antiofuscante em sobrepor', 'Câmara de homogeneização de luz', 'Montagem limpa'],
    maxStripWidth: '10mm',
    diffuser: 'Acrílico Difusor Recuado',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1541123437800-1bb1317badc2?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0005',
    name: 'Perfil LED Sobrepor De Canto 17x17mm',
    code: 'PSL0005',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 17,
    height: 17,
    description: 'Perfil angular de 45° de sobrepor para cantos e junções teto-parede ou móvel-parede. Facho direcionado para o centro do ambiente.',
    applications: ['Cantos de armários e bancadas', 'Junção teto e parede', 'Vitrines e expositores em ângulo', 'Closets e prateleiras de canto'],
    features: ['Ângulo perfeito de 45 graus', 'Aproveitamento ideal de cantos mortos', 'Fixação direta angular'],
    maxStripWidth: '10mm',
    diffuser: 'Acrílico Angular Leitoso',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: true,
    image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0007',
    name: 'Perfil LED Sobrepor 24x20mm',
    code: 'PSL0007',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 24,
    height: 20,
    description: 'Perfil de sobrepor de médio porte. Oferece alta eficiência de iluminação direta em forros de concreto ou lajes sem rebaixo.',
    applications: ['Lajes maciças sem forro de gesso', 'Escritórios e estúdios estilo industrial', 'Garagens residenciais e gourmet', 'Varandas'],
    features: ['Corpo robusto em alumínio extrudado', 'Ótima dissipação térmica', 'Fixação segura por presilhas duráveis'],
    maxStripWidth: '12mm',
    diffuser: 'Policarbonato Difusor Anti-UV',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0008',
    name: 'Perfil LED Sobrepor 35x12mm',
    code: 'PSL0008',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 35,
    height: 12,
    description: 'Perfil plano de sobrepor com largura de 35mm. Visual marcante em lajes expostas e painéis de madeira de grande extensão.',
    applications: ['Teto de concreto aparente', 'Painéis de parede residenciais', 'Lojas e restaurantes', 'Recepções'],
    features: ['Projeção plana moderna', 'Distribuição de luz uniforme', 'Alta resistência mecânica'],
    maxStripWidth: '15mm',
    diffuser: 'Acrílico PMMA Leitoso',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0009',
    name: 'Perfil LED Sobrepor 35x20mm',
    code: 'PSL0009',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 35,
    height: 20,
    description: 'Perfil versátil de sobrepor para iluminação direta funcional. Permite fitas de LED de alta densidade para iluminação primária.',
    applications: ['Escritórios modernos e coworking', 'Salas de jantar e cozinhas', 'Corredores comerciais', 'Academias e estúdios'],
    features: ['Câmara profunda para luz homogênea', 'Pintura eletrostática de alto acabamento', 'Fácil instalação'],
    maxStripWidth: '15mm',
    diffuser: 'Acrílico Difusor PMMA',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0010',
    name: 'Perfil LED Sobrepor 35x35mm',
    code: 'PSL0010',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 35,
    height: 35,
    description: 'Perfil quadrado de sobrepor. Design geométrico simétrico ideal para composições arquitetônicas tridimensionais.',
    applications: ['Composições em grade no teto', 'Iluminação linear contínua em lajes', 'Espaços comerciais de design', 'Salas de jogos e lazer'],
    features: ['Seção quadrada perfeita 35x35mm', 'Alta rigidez estrutural', 'União perfeita em ângulos de 90°'],
    maxStripWidth: '15mm',
    diffuser: 'Policarbonato Difusor Leitoso',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0012',
    name: 'Perfil LED Sobrepor Rodateto 46x22mm',
    code: 'PSL0012',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 46,
    height: 22,
    description: 'Perfil rodateto de sobrepor. Instalado no encontro teto-parede para criar uma sanca de luz indireta de alta elegância sem reforma.',
    applications: ['Sancas perimetrais sem gesso', 'Salas de estar, jantar e dormitórios', 'Halls de entrada', 'Restaurantes'],
    features: ['Efeito de sanca indireta sem corte no gesso', 'Direcionamento suave da luz para o teto', 'Fixação simples na parede'],
    maxStripWidth: '12mm',
    diffuser: 'Acrílico Curvo Difusor',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0013',
    name: 'Perfil LED Sobrepor 50x24mm',
    code: 'PSL0013',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 50,
    height: 24,
    description: 'Perfil de sobrepor com largura estendida de 50mm. Permite acomodação de múltiplas fitas de LED ou drivers internos embutidos.',
    applications: ['Iluminação técnica comercial', 'Ambientes de pé-direito duplo', 'Lojas e depósitos de luxo', 'Salas de reunião'],
    features: ['Espaço para fita dupla', 'Excelente dissipação térmica', 'Compatível com tampas de topo herméticas'],
    maxStripWidth: '24mm',
    diffuser: 'Acrílico Opalino Leitoso',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0014',
    name: 'Perfil LED Sobrepor Indireta 65x40mm',
    code: 'PSL0014',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 65,
    height: 40,
    description: 'Perfil de iluminação indireta dupla (up & down) ou indireta de parede. Projeta a luz suavemente para cima e para os lados.',
    applications: ['Arandela contínua de parede', 'Sancas cenográficas', 'Salas de estar e salas de jantar', 'Dormitórios de casais'],
    features: ['Luz indireta e confortável que não ofusca', 'Construção técnica com refletor interno', 'Visual arquitetônico de alto padrão'],
    maxStripWidth: '18mm',
    diffuser: 'Policarbonato Difusor Duplo',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0015',
    name: 'Perfil LED Sobrepor Rodateto 113x65mm',
    code: 'PSL0015',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 113,
    height: 65,
    description: 'Perfil rodateto imponente para grande iluminação indireta. Substitui sancas tradicionais em projetos de grande escala.',
    applications: ['Grandes salas de estar e salões de festas', 'Recepções de hotéis e prédios corporativos', 'Restaurantes de luxo', 'Auditórios'],
    features: ['Projeção de luz indireta de altíssimo alcance', 'Formato arquitetônico majestoso', 'Alumínio de alta resistência mecânica'],
    maxStripWidth: '24mm',
    diffuser: 'Acrílico Especial de Alta Transmitância',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?q=80&w=800&auto=format&fit=crop',
  },

  // --- PENDENTE ---
  {
    id: 'psl0011',
    name: 'Perfil LED Sobrepor / Pendente 35x50mm',
    code: 'PSL0011',
    type: 'pendente',
    category: 'Pendente',
    width: 35,
    height: 50,
    description: 'Perfil com design minimalista versátil. Permite instalação direta sobrepor ou suspensa por cabos de aço como luminária pendente.',
    applications: ['Ilhas de cozinha e bancadas americanas', 'Mesas de jantar e de reunião', 'Estações de trabalho corporativas', 'Recepções'],
    features: ['Compatível com kits de suspensão por cabo de aço', 'Difusor em acrílico uniforme sem sombra', 'Pintura microtexturizada premium'],
    maxStripWidth: '15mm',
    diffuser: 'Acrílico Difusor Opalino PMMA',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?q=80&w=800&auto=format&fit=crop',
  },

  // --- NO FRAME ---
  {
    id: 'psl0032',
    name: 'Perfil LED Embutir No Frame 84x39mm',
    code: 'PSL0032',
    type: 'no-frame',
    category: 'No Frame',
    width: 84,
    height: 39,
    description: 'Perfil No Frame (sem bordas aparentes) para forro de gesso. O perfil é chumbado e emassado diretamente no gesso para acabamento 100% invisível.',
    applications: ['Teto de gesso e drywall sem abas', 'Salas de estar minimalistas de alto padrão', 'Galerias e museus', 'Escritórios de arquitetura'],
    features: ['Zero bordas metálicas aparentes', 'Integração 100% fluida com o gesso', 'Calha interna removível para manutenção rápida'],
    maxStripWidth: '15mm',
    diffuser: 'Acrílico Leitoso Especial Flush Fit',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0033',
    name: 'Perfil LED Embutir No Frame 91x60mm',
    code: 'PSL0033',
    type: 'no-frame',
    category: 'No Frame',
    width: 91,
    height: 60,
    description: 'Perfil No Frame profundo de 60mm. Permite criar rasgos de luz puras e sem bordas com altíssimo fluxo luminoso.',
    applications: ['Salas de conferência e auditórios', 'Halls de edifícios corporativos', 'Residências de luxo contemporâneas', 'Lojas de departamento'],
    features: ['Total eliminação de pontos e bordas', 'Profundidade de 60mm para difusão contínua', 'Manutenção facilitada por pressão'],
    maxStripWidth: '20mm',
    diffuser: 'Acrílico Leitoso PMMA Especial',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0035',
    name: 'Perfil LED Embutir No Frame 115x42mm',
    code: 'PSL0035',
    type: 'no-frame',
    category: 'No Frame',
    width: 115,
    height: 42,
    description: 'Perfil No Frame extra largo de 115mm. Projetado para criar grandes linhas de luz contínuas e imponentes totalmente integradas ao teto.',
    applications: ['Grandes livings e áreas sociais', 'Showrooms e concessionárias', 'Aeroportos e hotéis', 'Espaços de convenção'],
    features: ['Largura imponente de 115mm sem bordas', 'Chumbamento contínuo em gesso', 'Suporta fitas duplas/triplas'],
    maxStripWidth: '30mm',
    diffuser: 'Policarbonato Difusor Opalino Premium',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=800&auto=format&fit=crop',
  },

  // --- PERFIS ESPECIAIS (RIPADOS) ---
  {
    id: 'psl0016',
    name: 'Perfil Especial Ripado Indireto 22x145mm',
    code: 'PSL0016',
    type: 'especial',
    category: 'Perfis Especiais',
    width: 145,
    height: 22,
    description: 'Perfil de alumínio especial para painéis ripados com iluminação indireta. Cria um efeito de luz suave entre as ripas de alumínio ou madeira.',
    applications: ['Painéis ripados de salas de estar e TV', 'Fachadas residenciais e comerciais', 'Recepções e halls de elevadores', 'Varandas gourmet'],
    features: ['Disponível também nos acabamentos amadeirados Linheiro e Jequitibá', 'Parafusos de fixação ocultos sem emendas aparentes', 'Resistente a intempéries'],
    maxStripWidth: '12mm',
    diffuser: 'Difusor de Policarbonato com Difusão Indireta',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Linheiro Claro', 'Jequitibá'],
    lengths: ['3 metros', '6 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1541123437800-1bb1317badc2?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0017',
    name: 'Perfil Especial Ripado Direto 22x145mm',
    code: 'PSL0017',
    type: 'especial',
    category: 'Perfis Especiais',
    width: 145,
    height: 22,
    description: 'Perfil ripado de alumínio com canalete de iluminação direta embutido no topo da ripa. Combina revestimento ripado e iluminação funcional em um só produto.',
    applications: ['Fachadas externas iluminadas', 'Painéis de parede internos de destaque', 'Muros decorativos de jardim', 'Entradas de prédios'],
    features: ['Iluminação direta frontal integrada', 'Acabamentos amadeirados de alta fidelidade e durabilidade', 'Corte e encaixe sob medida de fábrica'],
    maxStripWidth: '12mm',
    diffuser: 'Acrílico Leitoso Frontal Anti-UV',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Linheiro Claro', 'Jequitibá'],
    lengths: ['3 metros', '6 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=800&auto=format&fit=crop',
  }
];

export const ARTICLES: BlogArticle[] = [
  {
    id: 'artigo-reducao-consumo-led',
    slug: 'quanto-a-iluminacao-em-led-reduz-no-consumo-de-energia',
    title: 'Quanto a iluminação em LED reduz no consumo de energia frente à lâmpada tradicional',
    date: '15 Mai 2026',
    category: 'Eficiência Energética',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
    excerpt: 'Comparativo detalhado de consumo em kWh, dissipação térmica do perfil de alumínio e redução de custos elétricos na transição da iluminação incandescente e fluorescente para LED linear.',
    content: `A substituição de sistemas convencionais por perfis lineares de LED representa uma das decisões mais eficientes em termos de economia operacional e qualidade luminotécnica.

### 1. Eficiência Energética Superior (Até 80% de Redução)
Os perfis de alumínio Pasilux com dissipação técnica otimizada permitem que as fitas de LED operem em temperaturas térmicas seguras (inferiores a 50°C), prolongando sua vida útil para além de 50.000 horas e reduzindo o consumo elétrico em até 80% comparado a sistemas tradicionais halógenos ou lâmpadas fluorescentes tubulares.

### 2. Dissipação Térmica do Alumínio
Uma das principais causas da queima prematura de fitas de LED instaladas diretamente em madeira ou gesso é o superaquecimento. O perfil de alumínio atua como um radiador passivo de calor, preservando o fluxo luminoso e a fidelidade cromática ao longo dos anos.

### 3. Conforto Visual e Reprodução de Cor (IRC > 90)
Com difusores de policarbonato e acrílico leitoso de alta transmitância, os perfis entregam iluminação difusa, homogênea e sem ofuscamento, ideal tanto para projetos residenciais quanto para lojas e ambientes de trabalho.`
  },
  {
    id: 'artigo-calculo-retorno-led',
    slug: 'quanto-tempo-leva-para-o-led-se-pagar-em-projeto-comercial',
    title: 'Quanto tempo leva para o LED se pagar em um projeto comercial: o cálculo de retorno',
    date: '28 Abr 2026',
    category: 'Economia & Planejamento',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=800&auto=format&fit=crop',
    excerpt: 'Entenda a equação de payback de retrofit luminotécnico em lojas, concessionárias, escritórios e galpões comerciais utilizando perfis de LED de alta durabilidade.',
    content: `Na busca por soluções que promovam uma economia mais sustentável e previsível, a iluminação em LED linear de alta performance apresenta o retorno sobre investimento (payback) mais veloz da infraestrutura predial.

### 1. O Cálculo Real de Payback
Em um espaço comercial de 300 m² operando 12 horas por dia, a transição para LED com perfis de alumínio amortiza todo o investimento de compra e instalação tipicamente entre 8 e 14 meses, considerando a redução direta de tarifa elétrica e a eliminação de trocas constantes de reatores e lâmpadas.

### 2. Redução Drástica de Custos de Manutenção
Substituir luminárias em pés-direitos duplos ou sancas requer andaimes, fechamento temporário de áreas de venda e contratação de eletricistas. Ao optar por extrusão robusta Pasilux e fitas de qualidade, o ciclo de intervenção cai drasticamente.

### 3. Alívio na Carga Térmica do Ar-Condicionado
Lâmpadas antigas convertem mais de 80% da energia elétrica consumida em calor indesejado. O LED reduz essa carga térmica, gerando economia adicional indireta nos compressores de climatização comercial.`
  },
  {
    id: 'artigo-led-leed-aqua',
    slug: 'led-e-certificacao-leed-aqua-o-que-considerar-na-especificacao',
    title: 'LED e certificação LEED/AQUA: o que considerar na especificação',
    date: '10 Mar 2026',
    category: 'Sustentabilidade & ESG',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=800&auto=format&fit=crop',
    excerpt: 'Parâmetros normativos, reciclabilidade do alumínio e métricas de eficiência energética exigidas para pontuação máxima em edifícios sustentáveis certificados.',
    content: `A obtenção de selos internacionais de sustentabilidade na construção civil (como LEED e AQUA-HQE) exige comprovação técnica dos materiais especificados no projeto luminotécnico.

### 1. Reciclabilidade do Alumínio Extrudado
A liga de alumínio de primeira fusão empregada pela Pasilux em Catanduva é 100% reciclável sem perda de integridade mecânica, pontuando diretamente no critério de ciclo de vida dos materiais e economia circular.

### 2. Ausência de Metais Tóxicos e Mercúrio
Diferente das tubulares fluorescentes, os sistemas LED não utilizam gases nocivos ou mercúrio pesado, facilitando os planos de gestão de resíduos sólidos exigidos pela certificação.

### 3. Integração com Automação e Dimerização (DALI / 0-10V)
Os perfis suportam fitas preparadas para protocolos de automação predial, permitindo colheita de luz natural (daylight harvesting) e redução automática do fluxo luminoso nos horários de maior incidência solar.`
  },
  {
    id: 'artigo-embutir-ou-sobrepor',
    slug: 'perfil-de-led-embutir-ou-sobrepor-qual-escolher-para-cada-forro',
    title: 'Perfil de LED embutir ou sobrepor: qual escolher pra cada tipo de forro?',
    date: '18 Fev 2026',
    category: 'Guia Técnico de Aplicação',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop',
    excerpt: 'Guia prático para especificar perfis com abas de embutir em gesso/drywall versus perfis de sobrepor em laje maciça, madeira ou superfícies sem rebaixo.',
    content: `A decisão entre perfis de embutir e perfis de sobrepor depende fundamentalmente da tipologia da superfície e da fase da obra.

### 1. Forros de Gesso Acartonado (Drywall) e Madeira: Perfis de Embutir
Quando existe rebaixo e espaço livre para recorte, os perfis de embutir com abas de acabamento (como os modelos PSL0006 e PSL0022) oferecem instalação limpa, cobrindo eventuais imperfeições de corte do forro com abas milimétricas.

### 2. Lajes de Concreto Aparente ou Alvenaria Maciça: Perfis de Sobrepor
Quando não é possível cortar a estrutura de concreto, os perfis de sobrepor (como PSL0007 e PSL0023) são fixados diretamente por presilhas de pressão ou furação de topo, criando um elemento linear arquitetônico proeminente e moderno.

### 3. Dica de Instalação Pasilux
Sempre verifique a profundidade útil do perfil em relação à largura da fita LED para assegurar a homogeneidade luminosa do difusor leitoso.`
  },
  {
    id: 'artigo-no-frame',
    slug: 'perfil-no-frame-o-que-e-quando-usar-no-seu-projeto',
    title: 'Perfil No Frame: o que é e quando vale a pena usar no seu projeto',
    date: '02 Fev 2026',
    category: 'Design Arquitetônico',
    readTime: '7 min',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=800&auto=format&fit=crop',
    excerpt: 'Descubra como os perfis No Frame (borda infinita) são emassados no drywall para criar rasgos de luz que parecem brotar da própria arquitetura.',
    content: `O perfil No Frame (ou borda infinita) é o padrão de excelência da arquitetura minimalista de alto padrão.

### 1. Como Funciona a Tecnologia No Frame
O perfil conta com abas perfuradas de alumínio que recebem tela de reforço e massa corrida (ou gesso), integrando-se completamente à superfície. Após a pintura, nenhuma borda metálica fica visível: apenas o difusor perfeitamente nivelado com o teto.

### 2. Quando Vale a Pena Usar
É recomendado para salas de estar, livings integrados, corredores longos e recepções corporativas onde a proposta visual é a limpeza absoluta de elementos salientes.

### 3. Cuidados na Execução
O perfil No Frame deve ser instalado na fase de estruturação do forro de drywall, antes do acabamento de pintura, garantindo alinhamento a laser dos módulos lineares.`
  },
  {
    id: 'artigo-cob-ou-smd',
    slug: 'cob-ou-smd-qual-fita-de-led-combina-com-cada-perfil-pasilux',
    title: 'COB ou SMD: qual fita de LED combina com cada perfil Pasilux?',
    date: '15 Jan 2026',
    category: 'Tecnologia Luminotécnica',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=800&auto=format&fit=crop',
    excerpt: 'Entenda a diferença técnica entre fitas COB e SMD tradicionais e saiba qual escolher de acordo com a profundidade do perfil de alumínio.',
    content: `A harmonia visual de um perfil iluminado depende do casamento técnico entre a fita LED instalada e a profundidade útil do canal de alumínio.

### 1. Fitas LED COB (Chip on Board)
Possuem centenas de micropontos de LED em linha contínua sob fósforo uniforme. São indispensáveis em perfis ultra-slim (como perfis de movelaria com menos de 10 mm de profundidade), pois garantem zero pontilhado visível mesmo com difusores finos.

### 2. Fitas LED SMD (2835, 5050, etc.)
Ideais para perfis mais profundos (acima de 15 mm a 20 mm) ou perfis de grande porte, onde a distância entre a fita e o difusor de acrílico já é suficiente para misturar os cones de luz e criar uma linha contínua.

### 3. Liberdade Pasilux
Nossos perfis são projetados com largura interna padronizada para receber qualquer fita comercial do mercado, permitindo que a sua revenda utilize os fornecedores de fita de sua confiança.`
  },
  {
    id: 'artigo-calculo-metragem',
    slug: 'como-calcular-a-metragem-linear-de-perfil-de-led-para-o-seu-projeto',
    title: 'Como calcular a metragem linear de perfil de LED para o seu projeto',
    date: '08 Jan 2026',
    category: 'Planejamento de Obra',
    readTime: '4 min',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800&auto=format&fit=crop',
    excerpt: 'Passo a passo para dimensionar barras de 2m, 3m ou 6m, calcular perdas em esquadrias de 45° e prever fontes de alimentação sem queda de tensão.',
    content: `Calcular com exatidão as barras de perfil e conexões evita desperdícios de material e atrasos na entrega da obra.

### 1. Medição e Margem de Corte
Sempre meça o perímetro real no forro ou na marcenaria montada. Em cantos a 90° com corte em meia-esquadria (45°), adicione uma margem de segurança de 5% a 10% para ajustes finos de encaixe.

### 2. Escolha do Comprimento de Barra
Barras de 3 metros e 6 metros proporcionam menos emendas visíveis em grandes vãos lineares, resultando em acabamento muito superior para galerias, fachadas e corredores.

### 3. Posição das Fontes e Alimentação
Planeje o posicionamento dos drivers a cada 5 metros de fita para evitar quedas de tensão no final da linha e assegurar brilho homogêneo de ponta a ponta.`
  },
  {
    id: 'artigo-corte-sob-medida',
    slug: 'perfil-de-led-sob-medida-como-funciona-o-corte-especial-de-fabrica',
    title: 'Perfil de LED sob medida: como funciona o corte especial de fábrica',
    date: '20 Dez 2025',
    category: 'Produção & Indústria',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?q=80&w=800&auto=format&fit=crop',
    excerpt: 'Conheça o serviço de corte de precisão em esquadrejadeiras industriais Pasilux, minimizando o trabalho manual e o descarte na obra.',
    content: `Para marcenarias de grande porte e instaladores de iluminação técnica, o corte de precisão realizado diretamente em fábrica agiliza o cronograma da obra.

### 1. Precisão Milimétrica Industrial
Com maquinário automatizado de corte a frio e lâminas específicas para perfis de alumínio anodizado, as extremidades saem da fábrica sem rebarbas ou deformações nas calhas do difusor.

### 2. Redução de Descarte no Canteiro
Ao solicitar lotes já cortados nas dimensões do projeto executivo, o profissional reduz em até 95% o desperdício de pontas de barra e o tempo de instalação no cliente.

### 3. Identificação por Ambientes
Os perfis podem ser etiquetados e embalados por cômodo ou trecho do projeto (ex: Sala, Quarto Casal, Cozinha), agilizando a separação na entrega da sua revenda.`
  }
];

export const PROJECTS_PORTFOLIO: ProjectPortfolioItem[] = [
  {
    id: 'proj-residencia-pinheiros',
    title: 'Residência Alto de Pinheiros',
    category: 'Residencial',
    location: 'São Paulo - SP',
    architect: 'Studio Arq + Design',
    lightingDesigner: 'Luz & Arte Projetos',
    usedProfiles: ['PSL0033 (No Frame 91x60mm)', 'PSL0018 (Movelaria 9x13mm)', 'PSL0020 (Movelaria 24x7mm)'],
    description: 'Rasgos contínuos No Frame integrados ao forro de gesso no living e sala de jantar, combinados com iluminação linear embutida na marcenaria de lâmina de nogueira.',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1000&auto=format&fit=crop',
    year: '2025'
  },
  {
    id: 'proj-corporativo-faria-lima',
    title: 'Sede Corporativa Faria Lima',
    category: 'Corporativo',
    location: 'São Paulo - SP',
    architect: 'Metro Arquitetura Corporativa',
    lightingDesigner: 'Eng. Roberto Santos',
    usedProfiles: ['PSL0012 (Pendente 35x35mm)', 'PSL0015 (Pendente 50x75mm)', 'PSL0022 (Embutir Aba)'],
    description: 'Luminárias pendentes customizadas sob medida em preto microtexturizado suspensas por cabos de aço sobre bancadas de reunião e open space.',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1000&auto=format&fit=crop',
    year: '2025'
  },
  {
    id: 'proj-cozinha-jardins',
    title: 'Cozinha Gourmet & Cristaleira Jardins',
    category: 'Marcenaria',
    location: 'São Paulo - SP',
    architect: 'Fernanda Lima Interiores',
    lightingDesigner: 'Lighting Studio SP',
    usedProfiles: ['PSL0018 (Movelaria 9x13mm)', 'PSL0021 (Movelaria 24x14mm)'],
    description: 'Iluminação ultra-slim 3000K embutida sob armários aéreos e no interior de cristaleiras de vidro reflecta, sem pontos de LED visíveis.',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=1000&auto=format&fit=crop',
    year: '2026'
  },
  {
    id: 'proj-fachada-alphaville',
    title: 'Painel Ripado & Fachada Alphaville',
    category: 'Residencial',
    location: 'Barueri - SP',
    architect: 'Carlos Eduardo Arquitetura',
    usedProfiles: ['PSL0016 (Ripado Indireto 22x145mm)', 'PSL0017 (Ripado Direto 22x145mm)'],
    description: 'Fachada monumental revestida com perfis ripados de alumínio em acabamento amadeirado Linheiro Claro com canais de LED integrados.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop',
    year: '2025'
  },
  {
    id: 'proj-loja-oscar-freire',
    title: 'Boutique Conceito Oscar Freire',
    category: 'Comercial',
    location: 'São Paulo - SP',
    architect: 'Vanguard Retail Design',
    lightingDesigner: 'Luminotécnica Avançada',
    usedProfiles: ['PSL0035 (No Frame 115x42mm)', 'PSL0019 (Assimétrico 10x30mm)'],
    description: 'Destaque para iluminação assimétrica de parede (wall washing) valorizando os produtos em exposição com alto índice de reprodução de cor.',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=1000&auto=format&fit=crop',
    year: '2026'
  },
  {
    id: 'proj-hotel-barra-sul',
    title: 'Lobby Hotel Boutique Costa Verde',
    category: 'Comercial',
    location: 'Balneário Camboriú - SC',
    architect: 'Costa & Associados',
    usedProfiles: ['PSL0033 (No Frame 91x60mm)', 'PSL0003 (Sobrepor 17x14mm)'],
    description: 'Composição de linhas de luz geométricas no teto do lobby criando uma atmosfera acolhedora e contemporânea na recepção.',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=1000&auto=format&fit=crop',
    year: '2025'
  }
];
