import { LEDProfile, BlogArticle, ProjectPortfolioItem } from './types';

export const PROFILES: LEDProfile[] = [
  // --- MOVELARIA ---
  {
    id: 'psl0018',
    name: 'Perfil LED Embutir Movelaria 9x13mm',
    code: 'PSL0018',
    type: 'movelaria',
    category: 'Movelaria',
    width: 9,
    height: 13,
    description: 'Perfil de iluminação compacto para móveis, forros, painéis de MDF e corian. Encaixe preciso nivelado à superfície com luz contínua de alta qualidade.',
    applications: ['Marcenaria fina e armários', 'Nichos e prateleiras de MDF', 'Closets e guarda-roupas', 'Espelhos e frentes de gaveta'],
    features: ['Travas de fixação ocultas', 'Excelente dissipação com fita LED COB', 'Difusor branco translúcido em acrílico PMMA'],
    maxStripWidth: '8mm',
    diffuser: 'Acrílico Translúcido Leitoso PMMA',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: true,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0020',
    name: 'Perfil LED Embutir Movelaria 24x7mm',
    code: 'PSL0020',
    type: 'movelaria',
    category: 'Movelaria',
    width: 24,
    height: 7,
    description: 'Perfil de embutir ultra-slim para móveis e divisórias. Altura reduzida de apenas 7mm, permitindo instalação em chapas finas de marcenaria sem comprometer a estrutura.',
    applications: ['Prateleiras de madeira sob medida', 'Painéis ripados de baixa espessura', 'Móveis de cozinha aéreos', 'Cabeceiras estofadas e MDF'],
    features: ['Design extra plano de 7mm', 'Instalação simples por presilhas de pressão', 'Compatível com fitas COB de alta potência'],
    maxStripWidth: '10mm',
    diffuser: 'Policarbonato Difusor Opalino Anti-UV',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: true,
    image: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0021',
    name: 'Perfil LED Embutir Movelaria 24x14mm',
    code: 'PSL0021',
    type: 'movelaria',
    category: 'Movelaria',
    width: 24,
    height: 14,
    description: 'Perfil para iluminação interna de móveis de alto padrão. Oferece câmara ótica de 14mm para eliminar completamente os pontos visíveis de LED.',
    applications: ['Closets e vitrines comerciais', 'Prateleiras de cozinhas e cristaleiras', 'Painéis decorativos de madeira', 'Estantes e bibliotecas'],
    features: ['Elimina o efeito pontilhado (No-dot)', 'Abas laterais elegantes para cobertura perfeita', 'Alta taxa de transmitância luminosa'],
    maxStripWidth: '12mm',
    diffuser: 'Acrílico Leitoso com Difusão Homogênea',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: true,
    image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0001',
    name: 'Perfil LED Sobrepor Movelaria 8x9mm',
    code: 'PSL0001',
    type: 'movelaria',
    category: 'Movelaria',
    width: 8,
    height: 9,
    description: 'Perfil plano ultra-discreto para sobrepor em superfícies com restrição de altura. Perfeito para aplicação sob armários e gavetas.',
    applications: ['Sob armários aéreos de cozinha', 'Iluminação interna de gavetas', 'Prateleiras expostas de vidro', 'Espelhos de banheiros'],
    features: ['Dimensão reduzida 8x9mm', 'Fixação direta limpa', 'Acompanha ponteiras e travas de fixação'],
    maxStripWidth: '8mm',
    diffuser: 'Policarbonato Fosco Acetinado',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: true,
    image: 'https://images.unsplash.com/photo-1541123437800-1bb1317badc2?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0003',
    name: 'Perfil LED Sobrepor Movelaria 17x14mm',
    code: 'PSL0003',
    type: 'movelaria',
    category: 'Movelaria',
    width: 17,
    height: 14,
    description: 'Perfil robusto de sobrepor para marcenaria e iluminação funcional. Ótima dissipação térmica para fitas LED de maior wattage.',
    applications: ['Bancadas de trabalho e home office', 'Balcões de atendimento e recepção', 'Prateleiras pesadas', 'Iluminação sob nichos'],
    features: ['Perfil estruturado resistente', 'Montagem rápida sobre MDF ou alvenaria', 'Compatível com múltiplos acessórios'],
    maxStripWidth: '10mm',
    diffuser: 'Acrílico Difusor PMMA',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: true,
    image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=800&auto=format&fit=crop',
  },

  // --- EMBUTIR ---
  {
    id: 'psl0019',
    name: 'Perfil LED Embutir Assimétrico 10x30mm',
    code: 'PSL0019',
    type: 'embutir',
    category: 'Embutir',
    width: 30,
    height: 10,
    description: 'Perfil de iluminação com facho de luz assimétrico direcionado, ideal para lavagem de paredes (wall washing) e contornos decorativos.',
    applications: ['Iluminação de destaque em paredes e quadros', 'Corredores e halls residenciais', 'Sinalização teto-parede', 'Recepções corporativas'],
    features: ['Facho de luz inclinado e direcionado', 'Proporciona iluminação indireta sem ofuscamento', 'Alumínio de alta pureza anodizado'],
    maxStripWidth: '10mm',
    diffuser: 'Policarbonato Asimétrico Difusor',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0022',
    name: 'Perfil LED Embutir com Aba 24x14mm',
    code: 'PSL0022',
    type: 'embutir',
    category: 'Embutir',
    width: 24,
    height: 14,
    description: 'Perfil clássico de embutir com abas laterais. Modelo mais vendido para rasgos de luz em forros de gesso e sancas residenciais.',
    applications: ['Rasgos de luz em teto de gesso e drywall', 'Iluminação geral em salas e quartos', 'Escritórios e salas de reunião', 'Corredores e passagens'],
    features: ['Abas laterais de acabamento perfeito', 'Suporta fitas de LED até 240 LEDs/m', 'Fixação firme por presilhas metálicas inclusas'],
    maxStripWidth: '12mm',
    diffuser: 'Policarbonato Translúcido Leitoso PMMA',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0023',
    name: 'Perfil LED Embutir 31x9mm',
    code: 'PSL0023',
    type: 'embutir',
    category: 'Embutir',
    width: 31,
    height: 9,
    description: 'Perfil slim largo de embutir. Oferece abas laterais estendidas para acabamento impecável em juntas de gesso ou painéis de parede.',
    applications: ['Teto de drywall e marcenaria de grande largura', 'Painéis de TV e cabeceiras', 'Salas de estar e salas de jantar', 'Lojas e showrooms'],
    features: ['Formato plano e discreto', 'Área de difusão mais larga', 'Acompanha travas e tampas de acabamento'],
    maxStripWidth: '12mm',
    diffuser: 'Acrílico Leitoso Anti-UV',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0024',
    name: 'Perfil LED Embutir 35x20mm',
    code: 'PSL0024',
    type: 'embutir',
    category: 'Embutir',
    width: 35,
    height: 20,
    description: 'Perfil médio/largo com 20mm de profundidade. Ideal para projetos luminotécnicos que exigem alto fluxo luminoso sem marcação de pontos.',
    applications: ['Iluminação principal em ambientes residenciais', 'Projetos arquitetônicos corporativos', 'Restaurantes e recepções de hotéis', 'Salas de reunião'],
    features: ['Câmara profunda para difusão contínua 100%', 'Estrutura reforçada de dissipação', 'Compatível com fitas de até 120 LEDs/m'],
    maxStripWidth: '15mm',
    diffuser: 'Acrílico Opalino de Alta Transmitância',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0025',
    name: 'Perfil LED Embutir 35x22mm',
    code: 'PSL0025',
    type: 'embutir',
    category: 'Embutir',
    width: 35,
    height: 22,
    description: 'Perfil de embutir profundo para projetos imponentes. Permite a instalação de fitas duplas ou fitas de altíssima densidade.',
    applications: ['Áreas sociais e salas integradas', 'Consultórios e clínicas', 'Lojas e galerias de arte', 'Salas de conferência'],
    features: ['Suporta fitas duplas em paralelo', 'Máxima homogeneidade luminosa', 'Excelente durabilidade do alumínio anodizado'],
    maxStripWidth: '18mm',
    diffuser: 'Policarbonato Difusor PMMA Leitoso',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0026',
    name: 'Perfil LED Embutir 46x12mm',
    code: 'PSL0026',
    type: 'embutir',
    category: 'Embutir',
    width: 46,
    height: 12,
    description: 'Perfil extra largo de embutir com abas estendidas. Cria linhas de luz largas marcantes em gesso e madeira.',
    applications: ['Rasgos de luz largos em halls e recepções', 'Corredores de hotéis e escritórios', 'Lojas de moda e vitrines', 'Projetos residenciais modernos'],
    features: ['Linha de luz imponente de 46mm de largura', 'Superfície difusora acetinada', 'Travas de fixação de ação rápida'],
    maxStripWidth: '20mm',
    diffuser: 'Acrílico Opalino Fosco',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0027',
    name: 'Perfil LED Embutir Tabica 47x40mm',
    code: 'PSL0027',
    type: 'embutir',
    category: 'Embutir',
    width: 47,
    height: 40,
    description: 'Perfil especial para aplicação em tabica metálica de forro de gesso. Cria o efeito visual de teto flutuante com luz indireta perfeita.',
    applications: ['Perímetro de tetos em gesso e drywall', 'Efeito de teto flutuante em salas e quartos', 'Sancas perimetrais integradas', 'Áreas corporativas'],
    features: ['Estrutura técnica para substituição de tabica tradicional', 'Iluminação indireta suave voltada para a parede', 'Acabamento limpo em alumínio'],
    maxStripWidth: '12mm',
    diffuser: 'Difusor de Policarbonato Anti-Ofuscamento',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0028',
    name: 'Perfil LED Embutir 50x35mm',
    code: 'PSL0028',
    type: 'embutir',
    category: 'Embutir',
    width: 50,
    height: 35,
    description: 'Perfil arquitetônico largo de alta potência. Projetado para funcionar como fonte de iluminação principal em grandes ambientes.',
    applications: ['Iluminação principal em escritórios e salas', 'Halls de entrada de edifícios e hotéis', 'Auditórios e salas de aula', 'Espaços comerciais'],
    features: ['Suporta fitas duplas paralelas de alta potência', 'Excelente gerenciamento térmico', 'Difusão total sem sombras'],
    maxStripWidth: '24mm',
    diffuser: 'Acrílico Leitoso Especial PMMA',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0029',
    name: 'Perfil LED Embutir Recuado 50x35mm',
    code: 'PSL0029',
    type: 'embutir',
    category: 'Embutir',
    width: 50,
    height: 35,
    description: 'Perfil recuado de alto conforto visual. O difusor fica posicionado no fundo do perfil, reduzindo o ofuscamento direto.',
    applications: ['Salas de TV e home theater', 'Dormitórios e áreas de descanso', 'Escritórios com estações de computador', 'Salas de reuniões'],
    features: ['Foco antiofuscante com difusor recuado', 'Conforto visual certificado', 'Visual arquitetônico sofisticado'],
    maxStripWidth: '20mm',
    diffuser: 'Acrílico Difusor Antireflexo',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0030',
    name: 'Perfil LED Embutir Wall Washer 66x38mm',
    code: 'PSL0030',
    type: 'embutir',
    category: 'Embutir',
    width: 66,
    height: 38,
    description: 'Perfil banhador de parede (Wall Washer) de embutir. Projetado com calha refletora parabólica para banhar paredes uniformemente.',
    applications: ['Banho de luz em paredes de pedra, tijolo ou texturizadas', 'Galerias de arte e exposições', 'Recepções e fachadas internas', 'Salas de estar em destaque'],
    features: ['Lente óptica reflexiva de alta precisão', 'Banhamento uniforme do topo ao piso', 'Construção reforçada'],
    maxStripWidth: '15mm',
    diffuser: 'Lente Parabólica com Difusor Direcionador',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0031',
    name: 'Perfil LED Embutir 71x18mm',
    code: 'PSL0031',
    type: 'embutir',
    category: 'Embutir',
    width: 71,
    height: 18,
    description: 'Perfil plano extra largo para teto e parede. Cria faixas luminosas marcantes em projetos minimalistas contemporâneos.',
    applications: ['Iluminação decorativa de impacto em grandes salas', 'Corredores corporativos e shopping centers', 'Salas de conferência', 'Vitrines'],
    features: ['Extrema largura de 71mm', 'Estrutura plana de embutir', 'Instalação rápida com presilhas estendidas'],
    maxStripWidth: '30mm',
    diffuser: 'Policarbonato Translúcido PMMA',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0034',
    name: 'Perfil LED Embutir Rodapé 100x18mm',
    code: 'PSL0034',
    type: 'embutir',
    category: 'Embutir',
    width: 100,
    height: 18,
    description: 'Perfil metálico estrutural para rodapé iluminado. Integra o rodapé ao piso com luz de balizamento voltada para baixo.',
    applications: ['Rodapé iluminado em corredores e salas', 'Balizamento noturno em suítes e banheiros', 'Hotéis e clínicas de saúde', 'Restaurantes'],
    features: ['Substitui o rodapé convencional', 'Resistente a impactos e limpeza de piso', 'Luz indireta orientada para o chão'],
    maxStripWidth: '12mm',
    diffuser: 'Acrílico Reforçado Anti-Impacto',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800&auto=format&fit=crop',
  },

  // --- SOBREPOR ---
  {
    id: 'psl0002',
    name: 'Perfil LED Sobrepor 17x7mm',
    code: 'PSL0002',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 17,
    height: 7,
    description: 'Perfil plano de sobrepor ultra-discreto. Aplicação direta em superfícies rígidas como lajes, marcenaria e alvenaria sem necessidade de corte.',
    applications: ['Iluminação sob armários de cozinha', 'Prateleiras e nichos decorativos', 'Cabeceiras de cama', 'Espelhos'],
    features: ['Apenas 7mm de espessura externa', 'Instalação rápida por presilhas metálicas', 'Acabamento limpo e durável'],
    maxStripWidth: '10mm',
    diffuser: 'Policarbonato Opalino PMMA',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: true,
    image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0004',
    name: 'Perfil LED Sobrepor Com Recuado 17x14mm',
    code: 'PSL0004',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 17,
    height: 14,
    description: 'Perfil de sobrepor com recuo do difusor. Combina a facilidade de instalação de sobrepor com o conforto visual do facho recuado.',
    applications: ['Home-office e bancadas de estudo', 'Corredores e passagens', 'Lojas e expositores de produtos', 'Salas de estar'],
    features: ['Efeito antiofuscante em sobrepor', 'Câmara de homogeneização de luz', 'Montagem limpa'],
    maxStripWidth: '10mm',
    diffuser: 'Acrílico Difusor Recuado',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1541123437800-1bb1317badc2?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0005',
    name: 'Perfil LED Sobrepor De Canto 17x17mm',
    code: 'PSL0005',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 17,
    height: 17,
    description: 'Perfil angular de 45° de sobrepor para cantos e junções teto-parede ou móvel-parede. Facho direcionado para o centro do ambiente.',
    applications: ['Cantos de armários e bancadas', 'Junção teto e parede', 'Vitrines e expositores em ângulo', 'Closets e prateleiras de canto'],
    features: ['Ângulo perfeito de 45 graus', 'Aproveitamento ideal de cantos mortos', 'Fixação direta angular'],
    maxStripWidth: '10mm',
    diffuser: 'Acrílico Angular Leitoso',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: true,
    image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0007',
    name: 'Perfil LED Sobrepor 24x20mm',
    code: 'PSL0007',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 24,
    height: 20,
    description: 'Perfil de sobrepor de médio porte. Oferece alta eficiência de iluminação direta em forros de concreto ou lajes sem rebaixo.',
    applications: ['Lajes maciças sem forro de gesso', 'Escritórios e estúdios estilo industrial', 'Garagens residenciais e gourmet', 'Varandas'],
    features: ['Corpo robusto em alumínio extrudado', 'Ótima dissipação térmica', 'Fixação segura por presilhas duráveis'],
    maxStripWidth: '12mm',
    diffuser: 'Policarbonato Difusor Anti-UV',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0008',
    name: 'Perfil LED Sobrepor 35x12mm',
    code: 'PSL0008',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 35,
    height: 12,
    description: 'Perfil plano de sobrepor com largura de 35mm. Visual marcante em lajes expostas e painéis de madeira de grande extensão.',
    applications: ['Teto de concreto aparente', 'Painéis de parede residenciais', 'Lojas e restaurantes', 'Recepções'],
    features: ['Projeção plana moderna', 'Distribuição de luz uniforme', 'Alta resistência mecânica'],
    maxStripWidth: '15mm',
    diffuser: 'Acrílico PMMA Leitoso',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0009',
    name: 'Perfil LED Sobrepor 35x20mm',
    code: 'PSL0009',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 35,
    height: 20,
    description: 'Perfil versátil de sobrepor para iluminação direta funcional. Permite fitas de LED de alta densidade para iluminação primária.',
    applications: ['Escritórios modernos e coworking', 'Salas de jantar e cozinhas', 'Corredores comerciais', 'Academias e estúdios'],
    features: ['Câmara profunda para luz homogênea', 'Pintura eletrostática de alto acabamento', 'Fácil instalação'],
    maxStripWidth: '15mm',
    diffuser: 'Acrílico Difusor PMMA',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0010',
    name: 'Perfil LED Sobrepor 35x35mm',
    code: 'PSL0010',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 35,
    height: 35,
    description: 'Perfil quadrado de sobrepor. Design geométrico simétrico ideal para composições arquitetônicas tridimensionais.',
    applications: ['Composições em grade no teto', 'Iluminação linear contínua em lajes', 'Espaços comerciais de design', 'Salas de jogos e lazer'],
    features: ['Seção quadrada perfeita 35x35mm', 'Alta rigidez estrutural', 'União perfeita em ângulos de 90°'],
    maxStripWidth: '15mm',
    diffuser: 'Policarbonato Difusor Leitoso',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0012',
    name: 'Perfil LED Sobrepor Rodateto 46x22mm',
    code: 'PSL0012',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 46,
    height: 22,
    description: 'Perfil rodateto de sobrepor. Instalado no encontro teto-parede para criar uma sanca de luz indireta de alta elegância sem reforma.',
    applications: ['Sancas perimetrais sem gesso', 'Salas de estar, jantar e dormitórios', 'Halls de entrada', 'Restaurantes'],
    features: ['Efeito de sanca indireta sem corte no gesso', 'Direcionamento suave da luz para o teto', 'Fixação simples na parede'],
    maxStripWidth: '12mm',
    diffuser: 'Acrílico Curvo Difusor',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0013',
    name: 'Perfil LED Sobrepor 50x24mm',
    code: 'PSL0013',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 50,
    height: 24,
    description: 'Perfil de sobrepor com largura estendida de 50mm. Permite acomodação de múltiplas fitas de LED ou drivers internos embutidos.',
    applications: ['Iluminação técnica comercial', 'Ambientes de pé-direito duplo', 'Lojas e depósitos de luxo', 'Salas de reunião'],
    features: ['Espaço para fita dupla', 'Excelente dissipação térmica', 'Compatível com tampas de topo herméticas'],
    maxStripWidth: '24mm',
    diffuser: 'Acrílico Opalino Leitoso',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0014',
    name: 'Perfil LED Sobrepor Indireta 65x40mm',
    code: 'PSL0014',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 65,
    height: 40,
    description: 'Perfil de iluminação indireta dupla (up & down) ou indireta de parede. Projeta a luz suavemente para cima e para os lados.',
    applications: ['Arandela contínua de parede', 'Sancas cenográficas', 'Salas de estar e salas de jantar', 'Dormitórios de casais'],
    features: ['Luz indireta e confortável que não ofusca', 'Construção técnica com refletor interno', 'Visual arquitetônico de alto padrão'],
    maxStripWidth: '18mm',
    diffuser: 'Policarbonato Difusor Duplo',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0015',
    name: 'Perfil LED Sobrepor Rodateto 113x65mm',
    code: 'PSL0015',
    type: 'sobrepor',
    category: 'Sobrepor',
    width: 113,
    height: 65,
    description: 'Perfil rodateto imponente para grande iluminação indireta. Substitui sancas tradicionais em projetos de grande escala.',
    applications: ['Grandes salas de estar e salões de festas', 'Recepções de hotéis e prédios corporativos', 'Restaurantes de luxo', 'Auditórios'],
    features: ['Projeção de luz indireta de altíssimo alcance', 'Formato arquitetônico majestoso', 'Alumínio de alta resistência mecânica'],
    maxStripWidth: '24mm',
    diffuser: 'Acrílico Especial de Alta Transmitância',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Alumínio Natural'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?q=80&w=800&auto=format&fit=crop',
  },

  // --- PENDENTE ---
  {
    id: 'psl0011',
    name: 'Perfil LED Sobrepor / Pendente 35x50mm',
    code: 'PSL0011',
    type: 'pendente',
    category: 'Pendente',
    width: 35,
    height: 50,
    description: 'Perfil com design minimalista versátil. Permite instalação direta sobrepor ou suspensa por cabos de aço como luminária pendente.',
    applications: ['Ilhas de cozinha e bancadas americanas', 'Mesas de jantar e de reunião', 'Estações de trabalho corporativas', 'Recepções'],
    features: ['Compatível com kits de suspensão por cabo de aço', 'Difusor em acrílico uniforme sem sombra', 'Pintura microtexturizada premium'],
    maxStripWidth: '15mm',
    diffuser: 'Acrílico Difusor Opalino PMMA',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?q=80&w=800&auto=format&fit=crop',
  },

  // --- NO FRAME ---
  {
    id: 'psl0032',
    name: 'Perfil LED Embutir No Frame 84x39mm',
    code: 'PSL0032',
    type: 'no-frame',
    category: 'No Frame',
    width: 84,
    height: 39,
    description: 'Perfil No Frame (sem bordas aparentes) para forro de gesso. O perfil é chumbado e emassado diretamente no gesso para acabamento 100% invisível.',
    applications: ['Teto de gesso e drywall sem abas', 'Salas de estar minimalistas de alto padrão', 'Galerias e museus', 'Escritórios de arquitetura'],
    features: ['Zero bordas metálicas aparentes', 'Integração 100% fluida com o gesso', 'Calha interna removível para manutenção rápida'],
    maxStripWidth: '15mm',
    diffuser: 'Acrílico Leitoso Especial Flush Fit',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0033',
    name: 'Perfil LED Embutir No Frame 91x60mm',
    code: 'PSL0033',
    type: 'no-frame',
    category: 'No Frame',
    width: 91,
    height: 60,
    description: 'Perfil No Frame profundo de 60mm. Permite criar rasgos de luz puras e sem bordas com altíssimo fluxo luminoso.',
    applications: ['Salas de conferência e auditórios', 'Halls de edifícios corporativos', 'Residências de luxo contemporâneas', 'Lojas de departamento'],
    features: ['Total eliminação de pontos e bordas', 'Profundidade de 60mm para difusão contínua', 'Manutenção facilitada por pressão'],
    maxStripWidth: '20mm',
    diffuser: 'Acrílico Leitoso PMMA Especial',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0035',
    name: 'Perfil LED Embutir No Frame 115x42mm',
    code: 'PSL0035',
    type: 'no-frame',
    category: 'No Frame',
    width: 115,
    height: 42,
    description: 'Perfil No Frame extra largo de 115mm. Projetado para criar grandes linhas de luz contínuas e imponentes totalmente integradas ao teto.',
    applications: ['Grandes livings e áreas sociais', 'Showrooms e concessionárias', 'Aeroportos e hotéis', 'Espaços de convenção'],
    features: ['Largura imponente de 115mm sem bordas', 'Chumbamento contínuo em gesso', 'Suporta fitas duplas/triplas'],
    maxStripWidth: '30mm',
    diffuser: 'Policarbonato Difusor Opalino Premium',
    colors: ['Preto Microtexturizado', 'Branco Texturizado'],
    lengths: ['1 metro', '2 metros', '3 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=800&auto=format&fit=crop',
  },

  // --- PERFIS ESPECIAIS (RIPADOS) ---
  {
    id: 'psl0016',
    name: 'Perfil Especial Ripado Indireto 22x145mm',
    code: 'PSL0016',
    type: 'especial',
    category: 'Perfis Especiais',
    width: 145,
    height: 22,
    description: 'Perfil de alumínio especial para painéis ripados com iluminação indireta. Cria um efeito de luz suave entre as ripas de alumínio ou madeira.',
    applications: ['Painéis ripados de salas de estar e TV', 'Fachadas residenciais e comerciais', 'Recepções e halls de elevadores', 'Varandas gourmet'],
    features: ['Disponível também nos acabamentos amadeirados Linheiro e Jequitibá', 'Parafusos de fixação ocultos sem emendas aparentes', 'Resistente a intempéries'],
    maxStripWidth: '12mm',
    diffuser: 'Difusor de Policarbonato com Difusão Indireta',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Linheiro Claro', 'Jequitibá'],
    lengths: ['3 metros', '6 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1541123437800-1bb1317badc2?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'psl0017',
    name: 'Perfil Especial Ripado Direto 22x145mm',
    code: 'PSL0017',
    type: 'especial',
    category: 'Perfis Especiais',
    width: 145,
    height: 22,
    description: 'Perfil ripado de alumínio com canalete de iluminação direta embutido no topo da ripa. Combina revestimento ripado e iluminação funcional em um só produto.',
    applications: ['Fachadas externas iluminadas', 'Painéis de parede internos de destaque', 'Muros decorativos de jardim', 'Entradas de prédios'],
    features: ['Iluminação direta frontal integrada', 'Acabamentos amadeirados de alta fidelidade e durabilidade', 'Corte e encaixe sob medida de fábrica'],
    maxStripWidth: '12mm',
    diffuser: 'Acrílico Leitoso Frontal Anti-UV',
    colors: ['Preto Microtexturizado', 'Branco Texturizado', 'Linheiro Claro', 'Jequitibá'],
    lengths: ['3 metros', '6 metros'],
    isCobRecommended: false,
    image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=800&auto=format&fit=crop',
  }
];

export const ARTICLES: BlogArticle[] = [
  {
    id: 'artigo-revolucao-led',
    slug: 'iluminacao-led-revolucao-luminosa',
    title: 'A Iluminação em LED: Uma Revolução Luminosa para o Futuro',
    date: '15 Mai 2026',
    category: 'Sustentabilidade & Tecnologia',
    readTime: '6 min',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
    excerpt: 'A iluminação desempenha um papel fundamental em nossas vidas diárias. Não apenas torna os ambientes mais agradáveis e acolhedores, mas também desempenha um papel crucial na eficiência energética e na redução dos impactos ambientais.',
    content: `A iluminação desempenha um papel fundamental em nossas vidas diárias. Não apenas torna os ambientes mais agradáveis e acolhedores, mas também desempenha um papel crucial na eficiência energética e na redução dos impactos ambientais. À medida que a tecnologia evolui, uma das maiores revoluções na indústria da iluminação é a adoção em larga escala da iluminação em LED (Light Emitting Diode). Neste artigo, exploraremos a importância da iluminação em LED e como ela está moldando o futuro da iluminação.

### 1. Eficiência Energética Superior
Os perfis de alumínio com dissipação técnica otimizada permitem que as fitas de LED operem em temperaturas seguras, prolongando sua vida útil para além de 50.000 horas e reduzindo o consumo elétrico em até 80% comparado a sistemas tradicionais halógenos ou fluorescentes.

### 2. Integração Arquitetônica Total (No Frame & Embutir)
Com as linhas No Frame e de embutir ultra-slim, a luz passa a fazer parte da estrutura do imóvel. Não existem mais luminárias pesadas poluindo o campo visual: a arquitetura é realçada por rasgos e linhas contínuas de luz homogênea e sem pontos aparentes (No-Dot).

### 3. Conforto Visual e Reprodução de Cor (IRC > 90)
A tecnologia COB (Chip on Board) combinada com os difusores em acrílico leitoso PMMA e policarbonato anti-UV da Pasilux proporciona um índice de reprodução de cor elevado, valorizando texturas de pedras naturais, madeiras e tecidos em projetos de alto padrão.`
  },
  {
    id: 'artigo-economia-led',
    slug: 'economia-gerada-pela-iluminacao-led',
    title: 'A Economia Gerada pela Iluminação de LED em Projetos Comerciais e Residenciais',
    date: '28 Abr 2026',
    category: 'Economia & Planejamento',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=800&auto=format&fit=crop',
    excerpt: 'Na busca por soluções que promovam uma economia mais eficiente e sustentável, a iluminação em LED destaca-se como o investimento de retorno mais rápido na construção civil.',
    content: `Na busca por soluções que promovam uma economia mais eficiente e sustentável, a iluminação em LED se destaca como uma opção brilhante. Além de oferecer iluminação de alta qualidade, os perfis em alumínio extrudado proporcionam economia direta na manutenção e na conta de energia.

### 1. Durabilidade e Redução de Manutenção
Substituir lâmpadas em pés-direitos duplos ou sancas requer andaimes e mão de obra especializada. Ao especificar perfis de alumínio Pasilux com correta dissipação térmica, a vida útil do sistema é estendida, reduzindo drasticamente custos de manutenção predial.

### 2. Baixa Emissão de Calor
Diferente de lâmpadas antigas que convertiam a maior parte da energia em calor, o LED gera iluminação fria. Isso alivia a carga térmica dos ambientes, resultando em menor esforço dos sistemas de ar-condicionado e menor consumo global de eletricidade.`
  },
  {
    id: 'artigo-passo-sustentavel',
    slug: 'iluminacao-led-passo-sustentavel',
    title: 'Iluminação em LED: Um Passo Sustentável em Direção ao Futuro da Construção',
    date: '10 Mar 2026',
    category: 'Design Sustentável',
    readTime: '5 min',
    image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=800&auto=format&fit=crop',
    excerpt: 'Em um mundo onde a sustentabilidade é cada vez mais crucial, a escolha da iluminação certa desempenha um papel significativo na certificação de edifícios verdes (LEED / AQUA).',
    content: `Em um mundo onde a sustentabilidade é cada vez mais crucial, a escolha da iluminação certa desempenha um papel significativo na redução do impacto ambiental e na eficiência de recursos naturais.

### 1. Reciclabilidade do Alumínio
A liga de alumínio de alta pureza utilizada na extrusão dos perfis Pasilux é 100% reciclável sem perda de propriedades mecânicas, alinhando-se aos princípios da economia circular na indústria da construção.

### 2. Ausência de Metais Pesados
Os sistemas em LED não contêm mercúrio nem emitem radiação ultravioleta ou infravermelha, tornando os ambientes mais saudáveis e facilitando o descarte consciente ao término do ciclo de vida.`
  }
];

export const PROJECTS_PORTFOLIO: ProjectPortfolioItem[] = [
  {
    id: 'proj-residencia-pinheiros',
    title: 'Residência Alto de Pinheiros',
    category: 'Residencial',
    location: 'São Paulo - SP',
    architect: 'Studio Arq + Design',
    lightingDesigner: 'Luz & Arte Projetos',
    usedProfiles: ['PSL0033 (No Frame 91x60mm)', 'PSL0018 (Movelaria 9x13mm)', 'PSL0020 (Movelaria 24x7mm)'],
    description: 'Rasgos contínuos No Frame integrados ao forro de gesso no living e sala de jantar, combinados com iluminação linear embutida na marcenaria de lâmina de nogueira.',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1000&auto=format&fit=crop',
    year: '2025'
  },
  {
    id: 'proj-corporativo-faria-lima',
    title: 'Sede Corporativa Faria Lima',
    category: 'Corporativo',
    location: 'São Paulo - SP',
    architect: 'Metro Arquitetura Corporativa',
    lightingDesigner: 'Eng. Roberto Santos',
    usedProfiles: ['PSL0012 (Pendente 35x35mm)', 'PSL0015 (Pendente 50x75mm)', 'PSL0022 (Embutir Aba)'],
    description: 'Luminárias pendentes customizadas sob medida em preto microtexturizado suspensas por cabos de aço sobre bancadas de reunião e open space.',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1000&auto=format&fit=crop',
    year: '2025'
  },
  {
    id: 'proj-cozinha-jardins',
    title: 'Cozinha Gourmet & Cristaleira Jardins',
    category: 'Marcenaria',
    location: 'São Paulo - SP',
    architect: 'Fernanda Lima Interiores',
    lightingDesigner: 'Lighting Studio SP',
    usedProfiles: ['PSL0018 (Movelaria 9x13mm)', 'PSL0021 (Movelaria 24x14mm)'],
    description: 'Iluminação ultra-slim 3000K embutida sob armários aéreos e no interior de cristaleiras de vidro reflecta, sem pontos de LED visíveis.',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=1000&auto=format&fit=crop',
    year: '2026'
  },
  {
    id: 'proj-fachada-alphaville',
    title: 'Painel Ripado & Fachada Alphaville',
    category: 'Residencial',
    location: 'Barueri - SP',
    architect: 'Carlos Eduardo Arquitetura',
    usedProfiles: ['PSL0016 (Ripado Indireto 22x145mm)', 'PSL0017 (Ripado Direto 22x145mm)'],
    description: 'Fachada monumental revestida com perfis ripados de alumínio em acabamento amadeirado Linheiro Claro com canais de LED integrados.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop',
    year: '2025'
  },
  {
    id: 'proj-loja-oscar-freire',
    title: 'Boutique Conceito Oscar Freire',
    category: 'Comercial',
    location: 'São Paulo - SP',
    architect: 'Vanguard Retail Design',
    lightingDesigner: 'Luminotécnica Avançada',
    usedProfiles: ['PSL0035 (No Frame 115x42mm)', 'PSL0019 (Assimétrico 10x30mm)'],
    description: 'Destaque para iluminação assimétrica de parede (wall washing) valorizando os produtos em exposição com alto índice de reprodução de cor.',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=1000&auto=format&fit=crop',
    year: '2026'
  },
  {
    id: 'proj-hotel-barra-sul',
    title: 'Lobby Hotel Boutique Costa Verde',
    category: 'Comercial',
    location: 'Balneário Camboriú - SC',
    architect: 'Costa & Associados',
    usedProfiles: ['PSL0033 (No Frame 91x60mm)', 'PSL0003 (Sobrepor 17x14mm)'],
    description: 'Composição de linhas de luz geométricas no teto do lobby criando uma atmosfera acolhedora e contemporânea na recepção.',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=1000&auto=format&fit=crop',
    year: '2025'
  }
];
